# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.graph.find_all_cliques as module_0


def test_case_0():
    str_0 = "\x0c"
    dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0, str_0: str_0, str_0: str_0}
    var_0 = module_0.find_all_cliques(dict_0)


def test_case_1():
    dict_0 = {}
    var_0 = module_0.find_all_cliques(dict_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "b\\~7\r0$N z\"+'"
    module_0.find_all_cliques(str_0)


def test_case_3():
    str_0 = "M"
    str_1 = "vL[vnA,;NV2G<>&x8N"
    dict_0 = {str_0: str_0, str_1: str_0}
    var_0 = module_0.find_all_cliques(dict_0)
