# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.tree.max_path_sum as module_0


def test_case_0():
    none_type_0 = None
    var_0 = module_0.helper(none_type_0, none_type_0)
    assert var_0 == 0


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"s\x0b\xc0KA\x86dz\xa8\x9ei\x982R\x90"
    module_0.helper(bytes_0, bytes_0)


def test_case_2():
    none_type_0 = None
    var_0 = module_0.max_path_sum(none_type_0)
    assert var_0 == pytest.approx(-1e309, abs=0.01, rel=0.01)
    var_1 = module_0.helper(none_type_0, none_type_0)
    assert var_1 == 0
