# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import algorithms.tree.tree as module_0


def test_case_0():
    tree_node_0 = module_0.TreeNode()
    assert tree_node_0.val == 0
    tree_node_1 = module_0.TreeNode()
    assert tree_node_1.val == 0
