# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import algorithms.linkedlist.linkedlist as module_0


def test_case_0():
    none_type_0 = None
    singly_linked_list_node_0 = module_0.SinglyLinkedListNode(none_type_0)


def test_case_1():
    int_0 = -1129
    doubly_linked_list_node_0 = module_0.DoublyLinkedListNode(int_0)
