# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.stack.longest_abs_path as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"u\x87\xdd0\x83\xee7\x94o\xa81 \xa2\x1c\x8d\xc3"
    module_0.length_longest_path(bytes_0)
