# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.maths.sqrt_precision_factor as module_0


def test_case_0():
    complex_0 = 2j
    var_0 = module_0.square_root(complex_0)
    assert var_0 == (0.9999975186443927 + 1.0000068023369235j)


def test_case_1():
    bool_0 = False
    var_0 = module_0.square_root(bool_0)
    assert var_0 == pytest.approx(0.0, abs=0.01, rel=0.01)
    var_1 = module_0.square_root(var_0)
