# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import builtins as module_0
import algorithms.arrays.trimmean as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    object_0 = module_0.object()
    module_1.trimmean(object_0, object_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    list_0 = [bool_0]
    var_0 = module_1.trimmean(list_0, bool_0)
    assert var_0 == pytest.approx(0.0, abs=0.01, rel=0.01)
    int_0 = -1796
    module_1.trimmean(int_0, int_0)
