# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp.num_decodings as module_0
import builtins as module_1


def test_case_0():
    str_0 = "y"
    var_0 = module_0.num_decodings(str_0)
    assert var_0 == 1


def test_case_1():
    str_0 = "]0\x0bvBl(|vU#\t,"
    var_0 = module_0.num_decodings2(str_0)
    assert var_0 == 0
    var_1 = module_0.num_decodings(var_0)
    assert var_1 == 0


def test_case_2():
    str_0 = "y"
    var_0 = module_0.num_decodings2(str_0)
    assert var_0 == 1


def test_case_3():
    bool_0 = False
    var_0 = module_0.num_decodings2(bool_0)
    assert var_0 == 0


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "70\x0bv8l(|vU,"
    module_0.num_decodings(str_0)


def test_case_5():
    str_0 = "]0\x0bvBl(|vU#\t,"
    var_0 = module_0.num_decodings2(str_0)
    assert var_0 == 0


@pytest.mark.xfail(strict=True)
def test_case_6():
    str_0 = "\t2]0\x0bvBl(|vU#\t,"
    module_0.num_decodings2(str_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    str_0 = "0\x0bvBl(|vU,"
    var_0 = module_0.num_decodings2(str_0)
    assert var_0 == 0
    var_1 = module_1.object()
    var_2 = module_0.num_decodings(str_0)
    assert var_2 == 0
    module_0.num_decodings(var_1)


@pytest.mark.xfail(strict=True)
def test_case_8():
    str_0 = "-0=I4'YN"
    module_0.num_decodings2(str_0)


@pytest.mark.xfail(strict=True)
def test_case_9():
    str_0 = "\t2]0\x0bvBl(|vU#\t,"
    module_0.num_decodings(str_0)


@pytest.mark.xfail(strict=True)
def test_case_10():
    str_0 = "73\x0bv8l(|v$a"
    module_0.num_decodings2(str_0)


@pytest.mark.xfail(strict=True)
def test_case_11():
    none_type_0 = None
    var_0 = module_0.num_decodings(none_type_0)
    assert var_0 == 0
    var_1 = module_0.num_decodings2(none_type_0)
    assert var_1 == 0
    str_0 = "23\x0bv8l(|v$a"
    module_0.num_decodings2(str_0)
